// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/grpcpb/notifications.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint32                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RemindAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=remind_at,json=remindAt,proto3" json:"remind_at,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReminderRequest) Reset() {
	*x = AddReminderRequest{}
	mi := &file_internal_grpcpb_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReminderRequest) ProtoMessage() {}

func (x *AddReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcpb_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReminderRequest.ProtoReflect.Descriptor instead.
func (*AddReminderRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcpb_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *AddReminderRequest) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *AddReminderRequest) GetRemindAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RemindAt
	}
	return nil
}

func (x *AddReminderRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddReminderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReminderResponse) Reset() {
	*x = AddReminderResponse{}
	mi := &file_internal_grpcpb_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReminderResponse) ProtoMessage() {}

func (x *AddReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcpb_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReminderResponse.ProtoReflect.Descriptor instead.
func (*AddReminderResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpcpb_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *AddReminderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddReminderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_grpcpb_notifications_proto protoreflect.FileDescriptor

const file_internal_grpcpb_notifications_proto_rawDesc = "" +
	"\n" +
	"#internal/grpcpb/notifications.proto\x12\x06grpcpb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n" +
	"\x12AddReminderRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\rR\x06taskId\x127\n" +
	"\tremind_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bremindAt\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"E\n" +
	"\x13AddReminderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2Y\n" +
	"\x0fReminderService\x12F\n" +
	"\vAddReminder\x12\x1a.grpcpb.AddReminderRequest\x1a\x1b.grpcpb.AddReminderResponseB%Z#otus_project/internal/grpcpb;grpcpbb\x06proto3"

var (
	file_internal_grpcpb_notifications_proto_rawDescOnce sync.Once
	file_internal_grpcpb_notifications_proto_rawDescData []byte
)

func file_internal_grpcpb_notifications_proto_rawDescGZIP() []byte {
	file_internal_grpcpb_notifications_proto_rawDescOnce.Do(func() {
		file_internal_grpcpb_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpcpb_notifications_proto_rawDesc), len(file_internal_grpcpb_notifications_proto_rawDesc)))
	})
	return file_internal_grpcpb_notifications_proto_rawDescData
}

var file_internal_grpcpb_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpcpb_notifications_proto_goTypes = []any{
	(*AddReminderRequest)(nil),    // 0: grpcpb.AddReminderRequest
	(*AddReminderResponse)(nil),   // 1: grpcpb.AddReminderResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_internal_grpcpb_notifications_proto_depIdxs = []int32{
	2, // 0: grpcpb.AddReminderRequest.remind_at:type_name -> google.protobuf.Timestamp
	0, // 1: grpcpb.ReminderService.AddReminder:input_type -> grpcpb.AddReminderRequest
	1, // 2: grpcpb.ReminderService.AddReminder:output_type -> grpcpb.AddReminderResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_grpcpb_notifications_proto_init() }
func file_internal_grpcpb_notifications_proto_init() {
	if File_internal_grpcpb_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpcpb_notifications_proto_rawDesc), len(file_internal_grpcpb_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpcpb_notifications_proto_goTypes,
		DependencyIndexes: file_internal_grpcpb_notifications_proto_depIdxs,
		MessageInfos:      file_internal_grpcpb_notifications_proto_msgTypes,
	}.Build()
	File_internal_grpcpb_notifications_proto = out.File
	file_internal_grpcpb_notifications_proto_goTypes = nil
	file_internal_grpcpb_notifications_proto_depIdxs = nil
}
